version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html/
    environment:
      - ETSY_CLIENT_ID=your_client_id
      - ETSY_CLIENT_SECRET=your_client_secret
      - ETSY_REDIRECT_URI=http://localhost:8000/public/callback.php
      - ETSY_ACCESS_TOKEN=your_access_token_here
      - DB_HOST=db
      - DB_NAME=myappdb
      - DB_USER=myuser
      - DB_PASS=mypassword
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: myappdb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: